server:
  port: port
  debug: true
  read_timeout_seconds: 300
  write_timeout_seconds: 300

jwt:
  secret: demo
  duration_minutes: 15
  refresh_duration_minutes: 15
  max_refresh_minutes: 1440
  signing_algorithm: HS256

keycloaks:
  path_key: ./public.key
  realm: demo
  client_secret: demo
  client_id: demo-app
  server: http://localhost:port

redis:
  server: localhost:6379
  password: demo

application:
  min_password_strength: 0
  swagger_ui_path: third_party/swaggerui/dist